### ISSUE TITLE
Error while running dev server

### ISSUE THREAD

**Issue by SidharthRaveendran** [cbsrbiobank/bbweb#2]
I get this error while trying to run the dev server event after I've configured the `conf/application.conf` file

`CreationException: Unable to create injector, see the following errors: 1) Error injecting constructor, com.typesafe.config.ConfigException$Missing: No configuration setting found for key 'application' at org.biobank.TestData.<init>(TestData.scala:317) at org.biobank.modules.BbwebModule.configure(BbwebModule.scala:11) (via modules: com.google.inject.util.Modules$OverrideModule -> org.biobank.modules.BbwebModule) while locating org.biobank.TestData`

**Comment by nloyola** [comment]
It appears that your are missing the file `config/testdata.conf`. This file is created with default settings the first  time you run `sbt run`.

What OS and Java version are you using?

**Comment by nloyola** [comment]
Closing issue since no feedback was given.
